5 create tokenizer
Servostar/gemstone pull request #15
Opened 2024-04-15 20:19 UTC by flixm16

Created all tokens for symbols and keywords used in the base language.

keyword token starts with "Key" and  ends with the Keyword itself. Example: "KeyInt" for "int"
Value token starts with "Val"
Operator token starts with "Op" 
Compiler function token starts with "Fun"

single symbols don't have a token and can be used with with single quotes

Every Keyword was successful recognized

2024-04-16 09:59 UTC, Servostar commented
Operators either passed-through as character or token. Should be uniform -> pass Operator always as token

2024-04-16 10:00 UTC, Servostar commented
Missing floating point literals, got integer and string

2024-04-16 10:02 UTC, Servostar commented on src/yacc/parser.y
> +
Unnecessary line break

2024-04-16 10:02 UTC, Servostar commented on src/yacc/parser.y
> +    char *string;
Missing floating point

2024-04-16 10:05 UTC, Servostar commented on src/lex/lexer.l
> +"." return('.');
Operators should be uniform in types. Either pass as character OR as token

2024-04-16 10:05 UTC, Servostar commented on src/lex/lexer.l
> +
Sooo much whitespace

2024-04-16 10:06 UTC, Servostar requested changes
Missing floating point literal, make operator typing uniform, fix whitespace

2024-04-17 06:44 UTC, Servostar commented on src/lex/lexer.l
> +[-+]?[0-9]*\.[0-9]+ {yylval.real = atof(yytext); return(ValFloat);};
Remove sign in favor of a 'negate' operator. Meaning we shall implement no explicit sign into the language but instead negate a number in a expression instead.

2024-04-17 06:48 UTC, Servostar commented on src/yacc/parser.y
> +    float real;
Pass integer and floating point literals as string.
Let interpretation of bitwise represention and such loss to parser.

2024-04-17 07:46 UTC, Servostar approved these changes
Seems good

2024-04-17 13:20 UTC, SirTalksalot75 approved these changes

2024-04-17 13:23 UTC, merged