4 read source file
Servostar/gemstone pull request #25
Opened 2024-04-22 09:53 UTC by SirTalksalot75

2024-04-22 10:34 UTC, Servostar commented on src/main.c
> +    fclose(input);
Closing the file before its read. Should be closed after parsing. Consider registering a function which closes the handle
with `atexit()`

2024-04-22 10:34 UTC, Servostar commented on src/main.c
> +    yyin = input;
`yyin` should be an extern as its not explicetly defined. Causes error otherwise

`extern FILE* yyin;`

2024-04-22 10:34 UTC, flixm16 commented on src/main.c
> +    yyin = input;
compiler doesn't know yyin. please declare it

2024-04-22 10:34 UTC, Servostar commented on src/main.c
> +        printf("Error opening file!\n");
Consider using `ERROR` function from logging API. Can be done in the aftermath as separate issue.

2024-04-22 10:36 UTC, Servostar commented on src/main.c
> +    FILE* input = fopen("program.gem", "r");
Input file name could be configurable. Consider implementing a user configurable file name when parsing command line options in issue #6.

2024-04-22 10:37 UTC, Servostar requested changes
The code doesn't compile successfully.
Check the comments for possible follow up issues

2024-04-22 10:55 UTC, SirTalksalot75 commented on src/main.c
> +    fclose(input);
Done*

2024-04-22 10:55 UTC, SirTalksalot75 commented on src/main.c
> +    yyin = input;
Done*

2024-04-22 10:55 UTC, SirTalksalot75 commented on src/main.c
> +    yyin = input;
Done*

2024-04-22 11:04 UTC, Servostar commented on src/main.c
> +    yyin = input;
`input` cannot be passed directly as parameter to `atexit`. In order to implement the proposal, create a new function which calls `fclose(input)`. This functions name is then to be passed to `atexit`

2024-04-22 11:52 UTC, flixm16 commented on src/main.c
> +        ERROR("File couldn't be opened!");
instead of an error use fatal so that the compiler closes and does't get in an unknown behavior. error doesn't terminate the compiler

2024-04-22 14:05 UTC, flixm16 requested changes

2024-04-22 14:05 UTC, flixm16 commented on src/main.c
> +    FILE* input = fopen("program.gem", "r");
compiler crashes when no file is found. you should consider to change it so the compiler gets the file as an argument

2024-04-23 12:35 UTC, Servostar commented on src/main.c
> +    fclose(argv[1]);
`argv` is only accessible in function `main`.
Possible fix could be to store the opened file handle in `yyin` (needs to be done anyway)
and close `yyin` at the end (only after checking for `NULL` of course).

2024-04-23 12:35 UTC, Servostar commented on src/main.c
> +    atexit(close_file);
Could be moved to into `setup()`

2024-04-23 12:38 UTC, Servostar commented on src/main.c
On successfull opening of the file the handle should be stored into `yyin` so that the lexer and parser start reading from this file.

2024-04-23 12:39 UTC, Servostar requested changes
Code doesn't compile.
Parser doesn't read from input file upon sucessfull handle creation.

2024-04-23 13:22 UTC, flixm16 requested changes

2024-04-23 13:22 UTC, flixm16 commented on src/main.c
> +    atexit(close_file(filename);
consider maybe moving the whole "atexit(close file)" after the check  if the file has been opened. that way you don't have to check in a seperate function and you can just use "fclose(file)" in atexit().

2024-04-23 13:28 UTC, SirTalksalot75 commented on src/main.c
> +    atexit(close_file(filename);
good Idea, but I'll move atexit() to setup().
And dogde the bullet by using yyin.(TODO not yet implemented)

2024-04-26 14:24 UTC, Servostar approved these changes

2024-04-26 14:24 UTC, flixm16 approved these changes

2024-04-26 14:25 UTC, merged