added rules for operators
Servostar/gemstone pull request #45
Opened 2024-04-29 12:45 UTC by Servostar

Added rules for operators. These include:
- Arithmetic (`+`,`-`,`*`,`/`) + negate
- Logical (Equals)
- Boolean (And, Or, Xor, Not)
- Bitwise (And, Or, Xor, Not)

Operators have corresponding associativity , unary operators such as Not and Negate additionally have greater precedence.

2024-04-29 15:03 UTC, flixm16 commented
what about less and greater, less equals and greater equals? what about not equals?

2024-04-30 09:52 UTC, Servostar commented
Implemented greater, less operator.
Since no tokens for >=, <= or != exist, these operators won't be implemented

2024-05-05 19:01 UTC, flixm16 requested changes
prog.gem shouldn't be there

2024-05-06 08:35 UTC, flixm16 approved these changes

2024-05-06 08:48 UTC, merged