added parser rule for function calling
Servostar/gemstone pull request #46
Opened 2024-04-29 12:54 UTC by Servostar

Added a parser rule for detecting function calls.
A function is made out of an identifier and a list of expressions separated by commas.

2024-05-05 18:55 UTC, flixm16 requested changes
we declared that something like this should also be parsed
```
foo(ident1, ident2)(ident3)
```

2024-05-05 19:12 UTC, Servostar commented
> we declared that something like this should also be parsed
> 
> ```
> foo(ident1, ident2)(ident3)
> ```

Requested changes implemented

2024-05-06 08:08 UTC, SirTalksalot75 approved these changes

2024-05-06 08:40 UTC, flixm16 approved these changes

2024-05-06 08:52 UTC, merged