6 add mechanism to read and globally save options
Servostar/gemstone pull request #78
Opened 2024-05-15 11:14 UTC by SirTalksalot75

added mechanism to save and read options globally

2024-05-15 14:45 UTC, flixm16 requested changes

2024-05-15 14:45 UTC, flixm16 commented on src/main.c
> +            char option[10];
what if my argv[i] is not 12 symbols long?

2024-05-15 14:45 UTC, flixm16 commented on src/main.c
> +char options[5][10];
such a small limitation is bad. Limitations are bad. what if i want to have 20 Options? what is with 30? 2000? i dont want to change it all the time

2024-05-15 14:45 UTC, flixm16 commented on src/main.c
> +            strcpy(option, argv[i] + 2);
why do you copy it? argv and argc has the same informations. save them global and use these.

2024-05-15 14:45 UTC, flixm16 commented on src/main.c
> +            add_option(option);
why do you copy argv in options? is it possible to put argv in add_option?

2024-05-15 14:45 UTC, flixm16 commented on src/main.c
> +    if (num_options < 5 ) {
i also have to change the number of options here?

2024-05-15 14:45 UTC, Servostar commented
# Implementation proposal
(Based on a spontaneous idea)

May you please consider the following:
Instead of copying the arguments to a static buffer we can keep a copy of the `argc` value and `argv` pointer globally.
Since both are valid the entire duration of the app, we can search through them directly (instead of the static buffer).

```c
// store argc and arg from main globally
int argc;
char** argv;

size_t check_option(const char* name) {
    // directly search through argv 
    for (int i = 0; i < argc; i++) {
        if (strcmp(name, argv[i] + 2) == 0) {
            return 1;
        }
    }
    return 0;
}
```

2024-05-15 14:46 UTC, flixm16 commented
please resolve comments

2024-05-16 07:13 UTC, SirTalksalot75 commented on src/main.c
> +            char option[10];
the max size is 10, still works, its only the reservation that is 10.

2024-05-16 07:13 UTC, SirTalksalot75 commented on src/main.c
> +char options[5][10];
ye, but its about the implementation of the function, the changes on the options can be handeled when needed.

2024-05-16 07:15 UTC, SirTalksalot75 commented on src/main.c
> +    if (num_options < 5 ) {
ye, basically

2024-05-16 08:20 UTC, flixm16 requested changes

2024-05-16 08:20 UTC, flixm16 commented on src/main.c
> +char options[5][10];
why do i even need a restriction? make it variable

2024-05-16 08:20 UTC, flixm16 commented on src/main.c
> +            strcpy(option, argv[i] + 2);
strcpy results in undefined behavior when the destination is smaller than the source. you should add a check befor using something like that

2024-06-03 10:41 UTC, Servostar commented
Development switched to @Servostar

2024-06-03 10:41 UTC, closed without merging